// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: importerBase.proto

#include "importerBase.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_importerBase_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_importerBase_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Person2_PhoneNumber;
}  // namespace protobuf_importerBase_2eproto
namespace importerBase {
class Person2_PhoneNumberDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Person2_PhoneNumber>
      _instance;
} _Person2_PhoneNumber_default_instance_;
class Person2DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Person2>
      _instance;
} _Person2_default_instance_;
}  // namespace importerBase
namespace protobuf_importerBase_2eproto {
static void InitDefaultsPerson2_PhoneNumber() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::importerBase::_Person2_PhoneNumber_default_instance_;
    new (ptr) ::importerBase::Person2_PhoneNumber();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::importerBase::Person2_PhoneNumber::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Person2_PhoneNumber =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPerson2_PhoneNumber}, {}};

static void InitDefaultsPerson2() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::importerBase::_Person2_default_instance_;
    new (ptr) ::importerBase::Person2();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::importerBase::Person2::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Person2 =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPerson2}, {
      &protobuf_importerBase_2eproto::scc_info_Person2_PhoneNumber.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Person2_PhoneNumber.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Person2.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2_PhoneNumber, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2_PhoneNumber, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2_PhoneNumber, number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2_PhoneNumber, type_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, age_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, email_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, phone_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, string_arg5_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, int32_arg6_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, uint32_arg7_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, int64_arg8_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, uint64_arg9_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, double_arg10_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, float_arg11_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importerBase::Person2, bool_arg12_),
  0,
  2,
  1,
  ~0u,
  ~0u,
  ~0u,
  3,
  4,
  5,
  6,
  7,
  8,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::importerBase::Person2_PhoneNumber)},
  { 9, 26, sizeof(::importerBase::Person2)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::importerBase::_Person2_PhoneNumber_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::importerBase::_Person2_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "importerBase.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022importerBase.proto\022\014importerBase\"\214\003\n\007P"
      "erson2\022\014\n\004name\030\001 \002(\t\022\013\n\003age\030\002 \002(\005\022\r\n\005ema"
      "il\030\003 \001(\t\0220\n\005phone\030\004 \003(\0132!.importerBase.P"
      "erson2.PhoneNumber\022\023\n\013string_arg5\030\005 \003(\t\022"
      "\022\n\nint32_arg6\030\006 \003(\005\022\023\n\013uint32_arg7\030\007 \001(\r"
      "\022\022\n\nint64_arg8\030\010 \001(\003\022\023\n\013uint64_arg9\030\t \001("
      "\004\022\024\n\014double_arg10\030\n \001(\001\022\023\n\013float_arg11\030\013"
      " \001(\002\022\022\n\nbool_arg12\030\014 \001(\010\032R\n\013PhoneNumber\022"
      "\016\n\006number\030\001 \002(\t\0223\n\004type\030\002 \001(\0162\037.importer"
      "Base.Person2.PhoneType:\004HOME\"+\n\tPhoneTyp"
      "e\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 433);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "importerBase.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_importerBase_2eproto
namespace importerBase {
const ::google::protobuf::EnumDescriptor* Person2_PhoneType_descriptor() {
  protobuf_importerBase_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_importerBase_2eproto::file_level_enum_descriptors[0];
}
bool Person2_PhoneType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Person2_PhoneType Person2::MOBILE;
const Person2_PhoneType Person2::HOME;
const Person2_PhoneType Person2::WORK;
const Person2_PhoneType Person2::PhoneType_MIN;
const Person2_PhoneType Person2::PhoneType_MAX;
const int Person2::PhoneType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void Person2_PhoneNumber::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Person2_PhoneNumber::kNumberFieldNumber;
const int Person2_PhoneNumber::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Person2_PhoneNumber::Person2_PhoneNumber()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_importerBase_2eproto::scc_info_Person2_PhoneNumber.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:importerBase.Person2.PhoneNumber)
}
Person2_PhoneNumber::Person2_PhoneNumber(const Person2_PhoneNumber& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  number_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_number()) {
    number_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.number_);
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:importerBase.Person2.PhoneNumber)
}

void Person2_PhoneNumber::SharedCtor() {
  number_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = 1;
}

Person2_PhoneNumber::~Person2_PhoneNumber() {
  // @@protoc_insertion_point(destructor:importerBase.Person2.PhoneNumber)
  SharedDtor();
}

void Person2_PhoneNumber::SharedDtor() {
  number_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Person2_PhoneNumber::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Person2_PhoneNumber::descriptor() {
  ::protobuf_importerBase_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_importerBase_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Person2_PhoneNumber& Person2_PhoneNumber::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_importerBase_2eproto::scc_info_Person2_PhoneNumber.base);
  return *internal_default_instance();
}


void Person2_PhoneNumber::Clear() {
// @@protoc_insertion_point(message_clear_start:importerBase.Person2.PhoneNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      number_.ClearNonDefaultToEmptyNoArena();
    }
    type_ = 1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Person2_PhoneNumber::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:importerBase.Person2.PhoneNumber)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_number()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->number().data(), static_cast<int>(this->number().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "importerBase.Person2.PhoneNumber.number");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .importerBase.Person2.PhoneType type = 2 [default = HOME];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::importerBase::Person2_PhoneType_IsValid(value)) {
            set_type(static_cast< ::importerBase::Person2_PhoneType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                2, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:importerBase.Person2.PhoneNumber)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:importerBase.Person2.PhoneNumber)
  return false;
#undef DO_
}

void Person2_PhoneNumber::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:importerBase.Person2.PhoneNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string number = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->number().data(), static_cast<int>(this->number().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importerBase.Person2.PhoneNumber.number");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->number(), output);
  }

  // optional .importerBase.Person2.PhoneType type = 2 [default = HOME];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:importerBase.Person2.PhoneNumber)
}

::google::protobuf::uint8* Person2_PhoneNumber::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:importerBase.Person2.PhoneNumber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string number = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->number().data(), static_cast<int>(this->number().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importerBase.Person2.PhoneNumber.number");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->number(), target);
  }

  // optional .importerBase.Person2.PhoneType type = 2 [default = HOME];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:importerBase.Person2.PhoneNumber)
  return target;
}

size_t Person2_PhoneNumber::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:importerBase.Person2.PhoneNumber)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required string number = 1;
  if (has_number()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->number());
  }
  // optional .importerBase.Person2.PhoneType type = 2 [default = HOME];
  if (has_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Person2_PhoneNumber::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:importerBase.Person2.PhoneNumber)
  GOOGLE_DCHECK_NE(&from, this);
  const Person2_PhoneNumber* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Person2_PhoneNumber>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:importerBase.Person2.PhoneNumber)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:importerBase.Person2.PhoneNumber)
    MergeFrom(*source);
  }
}

void Person2_PhoneNumber::MergeFrom(const Person2_PhoneNumber& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:importerBase.Person2.PhoneNumber)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_number();
      number_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.number_);
    }
    if (cached_has_bits & 0x00000002u) {
      type_ = from.type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Person2_PhoneNumber::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:importerBase.Person2.PhoneNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Person2_PhoneNumber::CopyFrom(const Person2_PhoneNumber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:importerBase.Person2.PhoneNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Person2_PhoneNumber::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void Person2_PhoneNumber::Swap(Person2_PhoneNumber* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Person2_PhoneNumber::InternalSwap(Person2_PhoneNumber* other) {
  using std::swap;
  number_.Swap(&other->number_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(type_, other->type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Person2_PhoneNumber::GetMetadata() const {
  protobuf_importerBase_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_importerBase_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Person2::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Person2::kNameFieldNumber;
const int Person2::kAgeFieldNumber;
const int Person2::kEmailFieldNumber;
const int Person2::kPhoneFieldNumber;
const int Person2::kStringArg5FieldNumber;
const int Person2::kInt32Arg6FieldNumber;
const int Person2::kUint32Arg7FieldNumber;
const int Person2::kInt64Arg8FieldNumber;
const int Person2::kUint64Arg9FieldNumber;
const int Person2::kDoubleArg10FieldNumber;
const int Person2::kFloatArg11FieldNumber;
const int Person2::kBoolArg12FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Person2::Person2()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_importerBase_2eproto::scc_info_Person2.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:importerBase.Person2)
}
Person2::Person2(const Person2& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      phone_(from.phone_),
      string_arg5_(from.string_arg5_),
      int32_arg6_(from.int32_arg6_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  email_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_email()) {
    email_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.email_);
  }
  ::memcpy(&age_, &from.age_,
    static_cast<size_t>(reinterpret_cast<char*>(&bool_arg12_) -
    reinterpret_cast<char*>(&age_)) + sizeof(bool_arg12_));
  // @@protoc_insertion_point(copy_constructor:importerBase.Person2)
}

void Person2::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  email_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&age_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bool_arg12_) -
      reinterpret_cast<char*>(&age_)) + sizeof(bool_arg12_));
}

Person2::~Person2() {
  // @@protoc_insertion_point(destructor:importerBase.Person2)
  SharedDtor();
}

void Person2::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  email_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Person2::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Person2::descriptor() {
  ::protobuf_importerBase_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_importerBase_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Person2& Person2::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_importerBase_2eproto::scc_info_Person2.base);
  return *internal_default_instance();
}


void Person2::Clear() {
// @@protoc_insertion_point(message_clear_start:importerBase.Person2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  phone_.Clear();
  string_arg5_.Clear();
  int32_arg6_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      email_.ClearNonDefaultToEmptyNoArena();
    }
  }
  if (cached_has_bits & 252u) {
    ::memset(&age_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&float_arg11_) -
        reinterpret_cast<char*>(&age_)) + sizeof(float_arg11_));
  }
  bool_arg12_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Person2::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:importerBase.Person2)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "importerBase.Person2.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 age = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_age();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &age_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string email = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_email()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->email().data(), static_cast<int>(this->email().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "importerBase.Person2.email");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .importerBase.Person2.PhoneNumber phone = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_phone()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string string_arg5 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_string_arg5()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->string_arg5(this->string_arg5_size() - 1).data(),
            static_cast<int>(this->string_arg5(this->string_arg5_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "importerBase.Person2.string_arg5");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 int32_arg6 = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 48u, input, this->mutable_int32_arg6())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_int32_arg6())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 uint32_arg7 = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {
          set_has_uint32_arg7();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uint32_arg7_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 int64_arg8 = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {
          set_has_int64_arg8();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &int64_arg8_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint64 uint64_arg9 = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {
          set_has_uint64_arg9();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &uint64_arg9_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double double_arg10 = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(81u /* 81 & 0xFF */)) {
          set_has_double_arg10();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &double_arg10_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float float_arg11 = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(93u /* 93 & 0xFF */)) {
          set_has_float_arg11();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &float_arg11_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool bool_arg12 = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {
          set_has_bool_arg12();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &bool_arg12_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:importerBase.Person2)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:importerBase.Person2)
  return false;
#undef DO_
}

void Person2::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:importerBase.Person2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importerBase.Person2.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // required int32 age = 2;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->age(), output);
  }

  // optional string email = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->email().data(), static_cast<int>(this->email().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importerBase.Person2.email");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->email(), output);
  }

  // repeated .importerBase.Person2.PhoneNumber phone = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->phone_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->phone(static_cast<int>(i)),
      output);
  }

  // repeated string string_arg5 = 5;
  for (int i = 0, n = this->string_arg5_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->string_arg5(i).data(), static_cast<int>(this->string_arg5(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importerBase.Person2.string_arg5");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->string_arg5(i), output);
  }

  // repeated int32 int32_arg6 = 6;
  for (int i = 0, n = this->int32_arg6_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      6, this->int32_arg6(i), output);
  }

  // optional uint32 uint32_arg7 = 7;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->uint32_arg7(), output);
  }

  // optional int64 int64_arg8 = 8;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->int64_arg8(), output);
  }

  // optional uint64 uint64_arg9 = 9;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(9, this->uint64_arg9(), output);
  }

  // optional double double_arg10 = 10;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->double_arg10(), output);
  }

  // optional float float_arg11 = 11;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(11, this->float_arg11(), output);
  }

  // optional bool bool_arg12 = 12;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->bool_arg12(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:importerBase.Person2)
}

::google::protobuf::uint8* Person2::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:importerBase.Person2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importerBase.Person2.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required int32 age = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->age(), target);
  }

  // optional string email = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->email().data(), static_cast<int>(this->email().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importerBase.Person2.email");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->email(), target);
  }

  // repeated .importerBase.Person2.PhoneNumber phone = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->phone_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->phone(static_cast<int>(i)), deterministic, target);
  }

  // repeated string string_arg5 = 5;
  for (int i = 0, n = this->string_arg5_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->string_arg5(i).data(), static_cast<int>(this->string_arg5(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importerBase.Person2.string_arg5");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->string_arg5(i), target);
  }

  // repeated int32 int32_arg6 = 6;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteInt32ToArray(6, this->int32_arg6_, target);

  // optional uint32 uint32_arg7 = 7;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->uint32_arg7(), target);
  }

  // optional int64 int64_arg8 = 8;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->int64_arg8(), target);
  }

  // optional uint64 uint64_arg9 = 9;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(9, this->uint64_arg9(), target);
  }

  // optional double double_arg10 = 10;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->double_arg10(), target);
  }

  // optional float float_arg11 = 11;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(11, this->float_arg11(), target);
  }

  // optional bool bool_arg12 = 12;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->bool_arg12(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:importerBase.Person2)
  return target;
}

size_t Person2::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:importerBase.Person2)
  size_t total_size = 0;

  if (has_name()) {
    // required string name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  if (has_age()) {
    // required int32 age = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->age());
  }

  return total_size;
}
size_t Person2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:importerBase.Person2)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000005) ^ 0x00000005) == 0) {  // All required fields are present.
    // required string name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());

    // required int32 age = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->age());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated .importerBase.Person2.PhoneNumber phone = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->phone_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->phone(static_cast<int>(i)));
    }
  }

  // repeated string string_arg5 = 5;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->string_arg5_size());
  for (int i = 0, n = this->string_arg5_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->string_arg5(i));
  }

  // repeated int32 int32_arg6 = 6;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->int32_arg6_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->int32_arg6_size());
    total_size += data_size;
  }

  // optional string email = 3;
  if (has_email()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->email());
  }

  if (_has_bits_[0 / 32] & 248u) {
    // optional uint32 uint32_arg7 = 7;
    if (has_uint32_arg7()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->uint32_arg7());
    }

    // optional int64 int64_arg8 = 8;
    if (has_int64_arg8()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->int64_arg8());
    }

    // optional uint64 uint64_arg9 = 9;
    if (has_uint64_arg9()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->uint64_arg9());
    }

    // optional double double_arg10 = 10;
    if (has_double_arg10()) {
      total_size += 1 + 8;
    }

    // optional float float_arg11 = 11;
    if (has_float_arg11()) {
      total_size += 1 + 4;
    }

  }
  // optional bool bool_arg12 = 12;
  if (has_bool_arg12()) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Person2::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:importerBase.Person2)
  GOOGLE_DCHECK_NE(&from, this);
  const Person2* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Person2>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:importerBase.Person2)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:importerBase.Person2)
    MergeFrom(*source);
  }
}

void Person2::MergeFrom(const Person2& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:importerBase.Person2)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  phone_.MergeFrom(from.phone_);
  string_arg5_.MergeFrom(from.string_arg5_);
  int32_arg6_.MergeFrom(from.int32_arg6_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_email();
      email_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.email_);
    }
    if (cached_has_bits & 0x00000004u) {
      age_ = from.age_;
    }
    if (cached_has_bits & 0x00000008u) {
      uint32_arg7_ = from.uint32_arg7_;
    }
    if (cached_has_bits & 0x00000010u) {
      int64_arg8_ = from.int64_arg8_;
    }
    if (cached_has_bits & 0x00000020u) {
      uint64_arg9_ = from.uint64_arg9_;
    }
    if (cached_has_bits & 0x00000040u) {
      double_arg10_ = from.double_arg10_;
    }
    if (cached_has_bits & 0x00000080u) {
      float_arg11_ = from.float_arg11_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000100u) {
    set_bool_arg12(from.bool_arg12());
  }
}

void Person2::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:importerBase.Person2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Person2::CopyFrom(const Person2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:importerBase.Person2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Person2::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000005) != 0x00000005) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->phone())) return false;
  return true;
}

void Person2::Swap(Person2* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Person2::InternalSwap(Person2* other) {
  using std::swap;
  CastToBase(&phone_)->InternalSwap(CastToBase(&other->phone_));
  string_arg5_.InternalSwap(CastToBase(&other->string_arg5_));
  int32_arg6_.InternalSwap(&other->int32_arg6_);
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  email_.Swap(&other->email_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(age_, other->age_);
  swap(uint32_arg7_, other->uint32_arg7_);
  swap(int64_arg8_, other->int64_arg8_);
  swap(uint64_arg9_, other->uint64_arg9_);
  swap(double_arg10_, other->double_arg10_);
  swap(float_arg11_, other->float_arg11_);
  swap(bool_arg12_, other->bool_arg12_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Person2::GetMetadata() const {
  protobuf_importerBase_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_importerBase_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace importerBase
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::importerBase::Person2_PhoneNumber* Arena::CreateMaybeMessage< ::importerBase::Person2_PhoneNumber >(Arena* arena) {
  return Arena::CreateInternal< ::importerBase::Person2_PhoneNumber >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::importerBase::Person2* Arena::CreateMaybeMessage< ::importerBase::Person2 >(Arena* arena) {
  return Arena::CreateInternal< ::importerBase::Person2 >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
