// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: importer.proto

#include "importer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_importerBase_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_importerBase_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Person2;
}  // namespace protobuf_importerBase_2eproto
namespace importer {
class AddressBook2DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AddressBook2>
      _instance;
} _AddressBook2_default_instance_;
}  // namespace importer
namespace protobuf_importer_2eproto {
static void InitDefaultsAddressBook2() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::importer::_AddressBook2_default_instance_;
    new (ptr) ::importer::AddressBook2();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::importer::AddressBook2::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_AddressBook2 =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsAddressBook2}, {
      &protobuf_importerBase_2eproto::scc_info_Person2.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_AddressBook2.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importer::AddressBook2, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importer::AddressBook2, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importer::AddressBook2, people_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importer::AddressBook2, t1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importer::AddressBook2, t2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importer::AddressBook2, book_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::importer::AddressBook2, people_once_),
  ~0u,
  ~0u,
  ~0u,
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::importer::AddressBook2)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::importer::_AddressBook2_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "importer.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016importer.proto\022\010importer\032\022importerBase"
      ".proto\"\214\001\n\014AddressBook2\022%\n\006people\030\001 \003(\0132"
      "\025.importerBase.Person2\022\n\n\002t1\030\002 \003(\t\022\n\n\002t2"
      "\030\003 \003(\005\022\021\n\tbook_name\030\004 \001(\t\022*\n\013people_once"
      "\030\005 \001(\0132\025.importerBase.Person2"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 189);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "importer.proto", &protobuf_RegisterTypes);
  ::protobuf_importerBase_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_importer_2eproto
namespace importer {

// ===================================================================

void AddressBook2::InitAsDefaultInstance() {
  ::importer::_AddressBook2_default_instance_._instance.get_mutable()->people_once_ = const_cast< ::importerBase::Person2*>(
      ::importerBase::Person2::internal_default_instance());
}
void AddressBook2::clear_people() {
  people_.Clear();
}
void AddressBook2::clear_people_once() {
  if (people_once_ != NULL) people_once_->Clear();
  clear_has_people_once();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AddressBook2::kPeopleFieldNumber;
const int AddressBook2::kT1FieldNumber;
const int AddressBook2::kT2FieldNumber;
const int AddressBook2::kBookNameFieldNumber;
const int AddressBook2::kPeopleOnceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AddressBook2::AddressBook2()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_importer_2eproto::scc_info_AddressBook2.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:importer.AddressBook2)
}
AddressBook2::AddressBook2(const AddressBook2& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      people_(from.people_),
      t1_(from.t1_),
      t2_(from.t2_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  book_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_book_name()) {
    book_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.book_name_);
  }
  if (from.has_people_once()) {
    people_once_ = new ::importerBase::Person2(*from.people_once_);
  } else {
    people_once_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:importer.AddressBook2)
}

void AddressBook2::SharedCtor() {
  book_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  people_once_ = NULL;
}

AddressBook2::~AddressBook2() {
  // @@protoc_insertion_point(destructor:importer.AddressBook2)
  SharedDtor();
}

void AddressBook2::SharedDtor() {
  book_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete people_once_;
}

void AddressBook2::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AddressBook2::descriptor() {
  ::protobuf_importer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_importer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AddressBook2& AddressBook2::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_importer_2eproto::scc_info_AddressBook2.base);
  return *internal_default_instance();
}


void AddressBook2::Clear() {
// @@protoc_insertion_point(message_clear_start:importer.AddressBook2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  people_.Clear();
  t1_.Clear();
  t2_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      book_name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(people_once_ != NULL);
      people_once_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool AddressBook2::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:importer.AddressBook2)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .importerBase.Person2 people = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_people()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string t1 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_t1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->t1(this->t1_size() - 1).data(),
            static_cast<int>(this->t1(this->t1_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "importer.AddressBook2.t1");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 t2 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 24u, input, this->mutable_t2())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_t2())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string book_name = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_book_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->book_name().data(), static_cast<int>(this->book_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "importer.AddressBook2.book_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .importerBase.Person2 people_once = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_people_once()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:importer.AddressBook2)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:importer.AddressBook2)
  return false;
#undef DO_
}

void AddressBook2::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:importer.AddressBook2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .importerBase.Person2 people = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->people_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->people(static_cast<int>(i)),
      output);
  }

  // repeated string t1 = 2;
  for (int i = 0, n = this->t1_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->t1(i).data(), static_cast<int>(this->t1(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importer.AddressBook2.t1");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->t1(i), output);
  }

  // repeated int32 t2 = 3;
  for (int i = 0, n = this->t2_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      3, this->t2(i), output);
  }

  cached_has_bits = _has_bits_[0];
  // optional string book_name = 4;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->book_name().data(), static_cast<int>(this->book_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importer.AddressBook2.book_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->book_name(), output);
  }

  // optional .importerBase.Person2 people_once = 5;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_people_once(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:importer.AddressBook2)
}

::google::protobuf::uint8* AddressBook2::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:importer.AddressBook2)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .importerBase.Person2 people = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->people_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->people(static_cast<int>(i)), deterministic, target);
  }

  // repeated string t1 = 2;
  for (int i = 0, n = this->t1_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->t1(i).data(), static_cast<int>(this->t1(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importer.AddressBook2.t1");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->t1(i), target);
  }

  // repeated int32 t2 = 3;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteInt32ToArray(3, this->t2_, target);

  cached_has_bits = _has_bits_[0];
  // optional string book_name = 4;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->book_name().data(), static_cast<int>(this->book_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "importer.AddressBook2.book_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->book_name(), target);
  }

  // optional .importerBase.Person2 people_once = 5;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_people_once(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:importer.AddressBook2)
  return target;
}

size_t AddressBook2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:importer.AddressBook2)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .importerBase.Person2 people = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->people_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->people(static_cast<int>(i)));
    }
  }

  // repeated string t1 = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->t1_size());
  for (int i = 0, n = this->t1_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->t1(i));
  }

  // repeated int32 t2 = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->t2_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->t2_size());
    total_size += data_size;
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional string book_name = 4;
    if (has_book_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->book_name());
    }

    // optional .importerBase.Person2 people_once = 5;
    if (has_people_once()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *people_once_);
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AddressBook2::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:importer.AddressBook2)
  GOOGLE_DCHECK_NE(&from, this);
  const AddressBook2* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AddressBook2>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:importer.AddressBook2)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:importer.AddressBook2)
    MergeFrom(*source);
  }
}

void AddressBook2::MergeFrom(const AddressBook2& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:importer.AddressBook2)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  people_.MergeFrom(from.people_);
  t1_.MergeFrom(from.t1_);
  t2_.MergeFrom(from.t2_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_book_name();
      book_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.book_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_people_once()->::importerBase::Person2::MergeFrom(from.people_once());
    }
  }
}

void AddressBook2::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:importer.AddressBook2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AddressBook2::CopyFrom(const AddressBook2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:importer.AddressBook2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddressBook2::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->people())) return false;
  if (has_people_once()) {
    if (!this->people_once_->IsInitialized()) return false;
  }
  return true;
}

void AddressBook2::Swap(AddressBook2* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AddressBook2::InternalSwap(AddressBook2* other) {
  using std::swap;
  CastToBase(&people_)->InternalSwap(CastToBase(&other->people_));
  t1_.InternalSwap(CastToBase(&other->t1_));
  t2_.InternalSwap(&other->t2_);
  book_name_.Swap(&other->book_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(people_once_, other->people_once_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AddressBook2::GetMetadata() const {
  protobuf_importer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_importer_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace importer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::importer::AddressBook2* Arena::CreateMaybeMessage< ::importer::AddressBook2 >(Arena* arena) {
  return Arena::CreateInternal< ::importer::AddressBook2 >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
